### ISSUE TITLE
JsonResponseHandler returns text/html header?

### ISSUE THREAD

**Issue by EdwardIII** [texthtml/whoops-silex#4]
Not sure if this is an issue with Whoops or Silex+Whoops.

I use the JsonResponseHandler:

``` php
$app->register(new WhoopsSilex\WhoopsServiceProvider());
$app['whoops']->pushHandler(new Whoops\Handler\JsonResponseHandler);
```

In my response I get this header though:

```
Content-Type:text/html; charset=UTF-8
```

As far as I can see, Whoops is trying to do the right thing:

https://github.com/filp/whoops/blob/master/src/Whoops/Handler/JsonResponseHandler.php#L84

It does hit this pathway and add the Content-Type header:

``` php
        if (\Whoops\Util\Misc::canSendHeaders()) {
            header('Content-Type: application/json');
        }
```

And if I put a die before it returns Handler::QUIT then the response does come back with application/json:

``` php
        echo json_encode($response);
        die(); # I then see application/json as the header in the output
        return Handler::QUIT;
```

Any idea how I can diagnose whether this is a bug in Whoops or something that's happening between Whoops/Silex?

**Comment by mathroc** [comment]
hmm I'm gonna have to look into that, nothing obvious at first sight, it might be a bug in [whoops-pimple](https://github.com/texthtml/whoops-pimple/blob/master/src/WhoopsServiceProvider.php) too

**Comment by mathroc** [comment]
I can't reproduce the problem. here is what I tried:

``` php
<?php // index.php

include 'vendor/autoload.php';

use WhoopsSilex\WhoopsServiceProvider;

$app = new \Silex\Application;
$app->register(new WhoopsServiceProvider);
$app['whoops']->pushHandler(new Whoops\Handler\JsonResponseHandler);

throw new Exception("Error Processing Request");
```

``` json
{ // composer.json
    "require": {
        "silex/silex": "~2.0@dev",
        "texthtml/whoops-silex": "~1.0"
    }
}
```

and it gives me this response:

``` json
{"error":{"type":"Exception","message":"Error Processing Request","file":"\/data\/users\/mathieu\/www\/sandbox\/silex\/index.php","line":11}}
```

with the header `Content-Type:"application/json"`

can you try to make a simple test case so I can have a look ?

**Comment by EdwardIII** [comment]
Yes, let me try and reproduce with a simple test case. I'll ping here when it's up.

**Comment by mathroc** [comment]
ok I just got the same problem. and I can reproduce it with that:

``` php
use WhoopsSilex\WhoopsServiceProvider;

$app = new \Silex\Application;
$app->register(new WhoopsServiceProvider);
$app['whoops']->pushHandler(new Whoops\Handler\JsonResponseHandler);

$app->get('/', function() {
    throw new Exception("Error Processing Request");
});

$app->run();
```

I'll try to fix that soon
